config/routes.rb
Rails.application.routes.draw do


root to: "ideas#index"

  resources :ideas do
    resources :likes, only: [:create, :destroy]
    resources :ratings
      end

  resources :users, only: [:new, :create] do
    resources :likes, only: [:index]
  end

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  has_many :ratings, dependent: :destroy
belongs_to :user, optional:true

has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

def liked_by?(user)
 likes.exists?(user: user)
end

 def like_for(user)
   likes.find_by(user: user)
 end

end

app/models/like.rb
class Like < ApplicationRecord
belongs_to :user
belongs_to :idea

#the following validation guarantees that the user can only like
#a question once
validates :user_id, uniqueness: {scope: :idea_id}
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :idea
  belongs_to :user
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password
has_many :ratings
has_many :ideas
has_many :likes, dependent: :destroy
has_many :liked_ideas, through: :likes, source: :idea
validates :username, presence: true, uniqueness: {case_sensitive: false}
validates :password_digest, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

def user_signed_in?
  session[:user_id].present?
end
helper_method :user_signed_in?

def current_user
  @current_user ||= User.find_by_id session[:user_id] if user_signed_in?
end
helper_method :current_user

def authenticate_user!
  if !user_signed_in?
    redirect_to new_session_path, notice: 'You must be signed in!'
  end

end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  #before_action :find_idea, only: [:show, :edit, :update, :destroy]
  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json

  def show
    @idea = Idea.find params[:id]
    @user = @idea.user
   @rating = Rating.new
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new idea_params
    @idea.user = current_user

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def post_owner
   @post_owner = Idea.find(params[:user_id])
  end


    def set_idea
      @idea = Idea.find(params[:id])
    end


    def idea_params
      params.require(:idea).permit(:title, :description, :text)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


    def create
     idea = Idea.find(params[:idea_id])

      like = Like.new(user: current_user, idea: idea)

      if like.save
        redirect_to idea_path(idea), notice: 'Liked question!'
      else
        redirect_to idea_path(idea), alert: like.errors.full_messages.join(', ')
      end
    end

    def destroy
      like = Like.find(params[:id])
      if like.destroy
        redirect_to idea_path(like.idea), notice: 'Un-liked question!'
      else
        redirect_to idea_path(like.idea), alert: like.errors.full_messages.join(', ')
      end
    end
  end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index]
  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end

  # GET /ratings/1
  # GET /ratings/1.json
  def show
  end

  # GET /ratings/new
  def new
    @rating = Rating.new
  end

  # GET /ratings/1/edit
  def edit
    @rating = Rating.find(params[:id])
      @idea = Idea.find(params[:idea_id])
end

  # POST /ratings
  # POST /ratings.json
  def create
    @idea = Idea.find(params[:idea_id])
    @rating = Rating.new rating_params
       @rating.idea = @idea
       @rating.user  = current_user
       if @rating.save
     redirect_to idea_path(@idea)
    else
      render 'ideas/show'
    end
    # respond_to do |format|
    #   if @rating.save
    #     format.html { redirect_to @rating, notice: 'Rating was successfully created.' }
    #     format.json { render :show, status: :created, location: @rating }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @rating.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /ratings/1
  # PATCH/PUT /ratings/1.json
  # def update
  #   respond_to do |format|
  #     if @rating.update(rating_params)
  #       format.html { redirect_to idea_path, notice: 'Rating was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @idea }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @rating.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end
  def update
    @rating = Rating.find(params[:id])
    @idea  = Idea.find(params[:idea_id])
      if @rating.update rating_params
        redirect_to idea_path(@idea)
      else
        redirect_to root_path(@idea, @rating)
      end
    end



  # DELETE /ratings/1
  # DELETE /ratings/1.json
  def destroy
    @rating = Rating.find(params[:id])
    @idea = Idea.find(params[:idea_id])
     if @rating.destroy
      redirect_to idea_path(@idea)
     end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rating
      @rating = Rating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rating_params
      params.require(:rating).permit(:body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_username params[:username]
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Thank you for signing in'
    else
      flash.now[:alert] = 'Wrong credentials!'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Signed Out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def new
  @user = User.new
 end

 def create
 @user = User.new user_params
 if @user.save
   session[:user_id] = @user.id
   redirect_to root_path, notice: 'Thank you for signing up'
 else
   render :new
 end
end

private

  def user_params
  params.require(:user).permit([:username,
                                :password])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<%= form_for(idea) do |f| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_area :title %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/home.html.erb
<h1> home </h1>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table>
  <thead>

  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <h2><%= link_to idea.title, idea %></h2>
        <h4><%= idea.description %></h4>

      
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>

  <h1><%= @idea.title %></h1>
</p>

<p>
  <h3><%= @idea.description %></h3>
</p>

<p>
  <h3>Created by: <%= @user.username %></h3>
</p>


<% if current_user == @user %>
<%= link_to 'Edit', edit_idea_path(@idea) %>
<%= link_to 'Delete', @idea, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<%= link_to 'Back', ideas_path %>

<% if @idea.liked_by?(current_user) %>
    <%= link_to 'Unlike', idea_like_path(@idea, idea.like_for(current_user)), method: :delete %>
  <% else %>
    <%= link_to 'Like', idea_likes_path(@idea), method: :post %>
  <% end %>


<span><%= pluralize(@idea.likes.count, 'like') %></span>

<h1> Reviews </h1>


<h3> Create a Review </h1>

  <%= form_for [@idea, @rating] do |f| %>


<%= f.label :body %>
<%= f.text_area :body %>

<%= f.submit %>

<% end %>

<% @idea.ratings.each do |rating| %>
<h3><%=rating.body %></h3>
<% if current_user == rating.user %>
<%= link_to 'Edit', edit_idea_rating_path(@idea,rating) %>
<%= link_to 'Delete', idea_rating_path(@idea,rating),
                       method: :delete,
                       data: {confirm: 'Are you sure?'} %>
<% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <h2><%= 'Idea Factory' %></h2>  <%= link_to 'New Idea', new_idea_path  %>
      <% if user_signed_in? %>
  Hello <%= current_user.username %>,
  <%= link_to 'Sign Out', sessions_path, method: :delete %>
<% else %>
  <%= link_to 'Sign Up', new_user_path %>
  |
  <%= link_to 'Sign In', new_session_path %>
<% end %>

    <hr>
    <%= yield %>
  </body>
</html>

app/views/ratings/edit.html.erb
<h1>Edit Review</h1>


<%= form_for [@idea, @rating] do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>

  <%= link_to 'Back', ideas_path %>

<% end  %>

app/views/ratings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ratings</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ratings.each do |rating| %>
      <tr>
        <td><%= rating.body %></td>
        <td><%= link_to 'Show', rating %></td>
        <td><%= link_to 'Edit', edit_rating_path(rating) %></td>
        <td><%= link_to 'Destroy', rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h1>New Rating</h1>

<%= render 'form', rating: @rating %>

<%= link_to 'Back', ratings_path %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @rating.body %>
</p>

<%= link_to 'Edit', edit_idea_rating_path(@rating) %> |
<%= link_to 'Back', idea_path %>

app/views/users/new.html.erb
<h1> Sign Up </h1>


<%= form_for @user do |f| %>
<div class ="form-group">
  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control' %>
</div>
<div class ="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>
</div>
<%= f.submit 'Sign Up', class: 'btn btn-primary' %>
<% end %>